# Generated by Django 3.0.5 on 2020-05-01 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('price', models.FloatField(blank=True, null=True)),
                ('course_description', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoursesOrdered',
            fields=[
                ('course_ordered_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_ordered', models.BooleanField(default=False)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MohTech.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('courses_enrolled', models.ManyToManyField(to='MohTech.Courses')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('section_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MohTech.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MohTech.Courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MohTech.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=40)),
                ('project_description', models.TextField()),
                ('project_file', models.CharField(max_length=100)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MohTech.Courses')),
                ('project_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MohTech.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('is_ordered', models.BooleanField(default=False)),
                ('ordered_courses', models.ManyToManyField(to='MohTech.CoursesOrdered')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MohTech.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('lesson_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('lesson_name', models.CharField(max_length=100)),
                ('is_previewed', models.BooleanField(blank=True, default=False, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MohTech.Sections')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('comment_body', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MohTech.Lessons')),
            ],
        ),
    ]
