# Generated by Django 3.0.5 on 2020-05-03 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MohTech', '0004_certificatecompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatecompleted',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MohTech.Courses'),
        ),
    ]
