# Generated by Django 3.0.5 on 2020-05-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MohTech', '0005_auto_20200503_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatecompleted',
            name='lesson_watched',
            field=models.ManyToManyField(to='MohTech.Lessons'),
        ),
        migrations.AlterUniqueTogether(
            name='certificatecompleted',
            unique_together=set(),
        ),
    ]
