# Generated by Django 3.0.5 on 2020-05-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MohTech', '0006_auto_20200503_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
