# Generated by Django 3.0.5 on 2020-05-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MohTech', '0007_courses_course_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='lesson_video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
