# Generated by Django 3.0.5 on 2020-05-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MohTech', '0008_lessons_lesson_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_name_english',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(max_length=200),
        ),
    ]
